name: CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Build documenation
      uses: xu-cheng/latex-action@v2
      with:
        root_file: doc.tex
        working_directory: documentation

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          
      - name: Python Unit Test
        uses: onichandame/python-test-action@0.0.0
        with:
          deps_list: "requirements.txt"
          path: "."
          test_dir: "."
          pattern: "*.test.py"
                    
