name: test

on:
  [push, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Python Unit Test
        uses: fylein/python-pytest-github-action@v1
        with:
          args: pip3 install -r requirements.txt && pytest 
                    
