name: test

on:
  [push, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Python Unit Test
        uses: fylein/python-pytest-github-action@v1
        with:
          args: pip3 install -r requirements.txt && pytest urge_monitor
                    
